services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Exposes Redis on localhost:6379 for external access
    networks:
      - crawler-network

  web-crawler:
    build:
      context: . # Dockerfile is located in the current directory
    container_name: web-crawler
    environment:
      - REDIS_ADDR=redis:6379 # Static value as Redis is always reachable via this address
      - SEED_URL=https://www.nytimes.com # Dynamic environment variable
      - WORKER_COUNT=1000 # Dynamic environment variable
    depends_on:
      - redis # Ensures Redis starts before the web crawler
    networks:
      - crawler-network
    volumes:
      - ./output:/output # Maps the /output directory in the container to ./output on the host

networks:
  crawler-network:
    driver: bridge
