apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432       # Service Port
      targetPort: 5432 # Container Port